# outdated, using swww

preload = ~/Pictures/wallpapers/walls/island-night.png

wallpaper = HDMI-A-1,~/Pictures/wallpapers/walls/island-night.png
wallpaper = HDMI-A-2,~/Pictures/wallpapers/walls/island-night.png
# .. more monitors

# disable messages on bottom
splash = false

# fully disable ipc
# ipc = offA